#-------------------------------
# General Site Settings
title: Arun Teja Godavarthi | ZeoSpec
logo: zeospec.png # You can add own logo.
description: Arun Teja Godavarthi aka. ZeoSpec, is a Community Buider, a Rotaractor and an Entrepreneur, with deep love towards Open Source, Training, and exploring the uncharted paths.

og_img: arunnobag.png

#-------------------------------
# Author Settings
author:
  name: Arun Teja Godavarthi
  image: zeospec-4.jpg
  say-hello: Hello, Iâ€™m <strong>Arun Teja Godavarthi</strong>
  bio: aka' <strong>ZeoSpec</strong>.<br><br><strong>Community</strong>, <strong><a href="https://rtr.zeospec.com/" target="_blank">Rotaract</a></strong>, <strong>Open Source</strong>, <strong>Training</strong>, <strong>Entrepreneurship</strong>, and <strong>exploring the uncharted paths</strong>.

  # image: 01.jpg
  # bio: Designs, talks, and writes about <strong>web</strong>, <strong>ethics</strong>, <strong>privacy</strong>, and dev. I share design tutorials, free resources and inspiration. Loves <a href="#">music</a> & riding his bicycle.


#-------------------------------
# Contact links
linkedin: https://www.linkedin.com/in/zeospec/
twitter: https://twitter.com/ZeoSpec # Add your Twitter handle
facebook: https://facebook.com/ZeoSpec # Add your Facebook handle
instagram: https://instagram.com/ZeoSpec # Add your Instagram handle
# dribbble: https://dribbble.com/ # Add your Dribbble handle
# pinterest: https://pinterest.com/ # Add your Pinterest handle


#-------------------------------
# Comment Section (Disqus)
# disqus-identifier: # add your shortname for Disqus Comment. For example mr-brown
utterances: true

#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.
instagram-profile: zeospec # Add instagram username

#-------------------------------
# Google Analytics
google-analytics: G-0LLJ53Y3RH # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
subscribe__title: Subscribe
subscribe__subtitle: Stay up to date! Get all the latest updates delivered straight to your inbox.

mailchimp_subscription: false
mailchimp: zeospec.us4.list-manage.com/subscribe/post?u=23869bb983dc401df79867d66&amp;id=0dcc7f289a # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

google_form_subscription: false
google_form: https://docs.google.com/forms/d/e/1FAIpQLSfB3qsTYxgAcWdde5Jzq7JquR2ASwVR9myv9dy3ULH7UOM2vg/formResponse
formNamekey: entry.6950510
formEmailkey: entry.1470521357

convertkit_subscription: true
convertkit_form: https://app.convertkit.com/forms/1874147/subscriptions
convertkit_FNamekey: fields[first_name]
convertkit_Emailkey: email_address